<!DOCTYPE html>

<html>
  <head>
    <title>LOCALHOST'R</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">

    <meta name="apple-mobile-web-app-title" content="Localhost'r" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />

    <meta name="mobile-web-app-capable" content="yes">
    <meta name="format-detection" content="telephone=no">

    <!-- icons:png -->
    <link rel="icon" type="image/png" sizes="60x60" href="./LOCALHOSTR/assets/images/icons/Icon-60.png"/>
    <link rel="apple-touch-icon" type="image/png" sizes="120x120" href="./LOCALHOSTR/assets/images/icons/Icon-60@2x.png"/>
    <!-- endinject -->

    <!-- inject:css -->
    <link rel="stylesheet" href="./LOCALHOSTR/assets/css/styles.min.css">
    <!-- endinject -->

  </head>

  <body ng-app="localhostr">

    <!-- CONTENT -->
    <div ui-view="app"></div>

    <!-- GLOBAL VARS -->
    <script type="text/javascript">
        var API_URL = '<?php echo $this->getScriptUrl() ?>';
        var IP_ADDR = '<?php echo IP_ADDR ?>';
        var APP_FOLDER = '<?php echo APP_FOLDER ?>';
    </script>

    <!-- lib:js -->
    <script src="./LOCALHOSTR/assets/js/lib/angular.js"></script>
    <script src="./LOCALHOSTR/assets/js/lib/angular-ui-router.js"></script>
    <script src="./LOCALHOSTR/assets/js/lib/angular-translate.js"></script>
    <script src="./LOCALHOSTR/assets/js/lib/angular-translate-loader-static-files.js"></script>
    <!-- endinject -->

    <!-- core:js -->
    <script src="./LOCALHOSTR/assets/js/core/app.js"></script>
    <script src="./LOCALHOSTR/assets/js/core/classes.js"></script>
    <script src="./LOCALHOSTR/assets/js/core/controller.js"></script>
    <script src="./LOCALHOSTR/assets/js/core/directives.js"></script>
    <script src="./LOCALHOSTR/assets/js/core/filters.js"></script>
    <script src="./LOCALHOSTR/assets/js/core/services.js"></script>
    <!-- endinject -->
  </body>
</html>
